"""Default Guangxi Police College teaching reward policy data (2024 revision)."""

POLICY_VERSION = "2024"

DEFAULT_REWARD_RULES = [
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "national", "rank": "grand_prize", "amount": 120000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "national", "rank": "first_prize", "amount": 100000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "national", "rank": "second_prize", "amount": 80000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "provincial", "rank": "grand_prize", "amount": 60000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "provincial", "rank": "first_prize", "amount": 50000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "provincial", "rank": "second_prize", "amount": 30000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "municipal", "rank": "grand_prize", "amount": 8000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "municipal", "rank": "first_prize", "amount": 6000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "municipal", "rank": "second_prize", "amount": 4000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "school", "rank": "grand_prize", "amount": 3000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "school", "rank": "first_prize", "amount": 2000},
    {"category": "teaching_achievement", "subcategory": "教学成果奖", "level": "school", "rank": "second_prize", "amount": 1000},
    {"category": "major_construction", "subcategory": "特色专业/一流专业/现代产业学院", "level": "national", "rank": None, "amount": 60000},
    {"category": "major_construction", "subcategory": "特色专业/一流专业/现代产业学院", "level": "provincial", "rank": None, "amount": 40000},
    {"category": "major_construction", "subcategory": "特色专业/一流专业/现代产业学院", "level": "school", "rank": None, "amount": 10000},
    {"category": "course_construction", "subcategory": "精品/一流/示范课程", "level": "national", "rank": None, "amount": 50000},
    {"category": "course_construction", "subcategory": "精品/一流/示范课程", "level": "provincial", "rank": None, "amount": 30000},
    {"category": "textbook_construction", "subcategory": "教材出版20万字以上", "level": "school", "rank": None, "amount": 8000},
    {"category": "textbook_construction", "subcategory": "教材出版20万字以下", "level": "school", "rank": None, "amount": 6000},
    {"category": "textbook_construction", "subcategory": "优秀教材奖", "level": "national", "rank": "first_prize", "amount": 50000},
    {"category": "textbook_construction", "subcategory": "优秀教材奖", "level": "national", "rank": "second_prize", "amount": 30000},
    {"category": "textbook_construction", "subcategory": "优秀教材奖", "level": "national", "rank": "third_prize", "amount": 20000},
    {"category": "textbook_construction", "subcategory": "优秀教材奖", "level": "provincial", "rank": "first_prize", "amount": 15000},
    {"category": "textbook_construction", "subcategory": "优秀教材奖", "level": "provincial", "rank": "second_prize", "amount": 10000},
    {"category": "textbook_construction", "subcategory": "优秀教材奖", "level": "provincial", "rank": "third_prize", "amount": 5000},
    {"category": "practice_teaching", "subcategory": "示范性实训基地/校外实践教学基地", "level": "national", "rank": None, "amount": 80000},
    {"category": "practice_teaching", "subcategory": "重点实验室", "level": "national", "rank": None, "amount": 80000},
    {"category": "practice_teaching", "subcategory": "重点实验室", "level": "provincial", "rank": None, "amount": 30000},
    {"category": "practice_teaching", "subcategory": "示范性实训基地/校外实践教学基地", "level": "provincial", "rank": None, "amount": 20000},
    {"category": "teacher_team", "subcategory": "优秀教学团队", "level": "national", "rank": None, "amount": 60000},
    {"category": "teacher_team", "subcategory": "优秀教学团队", "level": "provincial", "rank": None, "amount": 30000},
    {"category": "teacher_team", "subcategory": "优秀教学团队", "level": "school", "rank": None, "amount": 10000},
    {"category": "teacher_team", "subcategory": "教学名师", "level": "national", "rank": None, "amount": 50000},
    {"category": "teacher_team", "subcategory": "教学名师", "level": "provincial", "rank": None, "amount": 30000},
    {"category": "teacher_team", "subcategory": "教学名师", "level": "school", "rank": None, "amount": 5000},
    {"category": "teacher_team", "subcategory": "教学新秀", "level": "school", "rank": None, "amount": 2000},
    {"category": "teaching_reform", "subcategory": "重点/重大项目", "level": "national", "rank": "key", "amount": 30000, "staged": True},
    {"category": "teaching_reform", "subcategory": "重点/重大项目", "level": "national", "rank": "major", "amount": 30000, "staged": True},
    {"category": "teaching_reform", "subcategory": "一般项目", "level": "national", "rank": "general", "amount": 15000, "staged": True},
    {"category": "teaching_reform", "subcategory": "本科教改重点项目", "level": "provincial", "rank": "key", "amount": 10000, "staged": True},
    {"category": "teaching_reform", "subcategory": "本科教改一般A类/职教重点", "level": "provincial", "rank": "A", "amount": 6000, "staged": True},
    {"category": "teaching_reform", "subcategory": "本科教改一般B类/职教一般", "level": "provincial", "rank": "B", "amount": 3000, "staged": True},
    {"category": "teaching_quality", "subcategory": "教学质量奖", "level": "school", "rank": "first_prize", "amount": 3000},
    {"category": "teaching_quality", "subcategory": "教学质量奖", "level": "school", "rank": "second_prize", "amount": 2000},
    {"category": "teaching_quality", "subcategory": "教学质量奖", "level": "school", "rank": "third_prize", "amount": 1000},
    {"category": "lecture_competition", "subcategory": "讲课比赛奖", "level": "school", "rank": "first_prize", "amount": 3000},
    {"category": "lecture_competition", "subcategory": "讲课比赛奖", "level": "school", "rank": "second_prize", "amount": 2000},
    {"category": "lecture_competition", "subcategory": "讲课比赛奖", "level": "school", "rank": "third_prize", "amount": 1000},
    {"category": "sanquan_education", "subcategory": "三全育人综合改革示范校", "level": "national", "rank": None, "amount": 80000},
    {"category": "sanquan_education", "subcategory": "三全育人综合改革示范校", "level": "provincial", "rank": None, "amount": 40000},
    {"category": "sanquan_education", "subcategory": "三全育人综合改革示范院系", "level": "national", "rank": None, "amount": 40000},
    {"category": "sanquan_education", "subcategory": "三全育人综合改革示范院系", "level": "provincial", "rank": None, "amount": 20000},
    {"category": "teaching_management", "subcategory": "虚拟教研室/示范中心", "level": "national", "rank": None, "amount": 50000},
    {"category": "teaching_management", "subcategory": "虚拟教研室/示范中心", "level": "provincial", "rank": None, "amount": 30000},
    {"category": "teaching_management", "subcategory": "基层教学组织", "level": "provincial", "rank": None, "amount": 20000},
    {"category": "teaching_management", "subcategory": "教学管理工作先进单位", "level": "school", "rank": None, "amount": 15000},
    {"category": "teaching_management", "subcategory": "教研室工作先进单位", "level": "school", "rank": None, "amount": 5000},
]

for scope, amounts in {
    "group": {
        ("national", "grand_prize"): 30000, ("national", "first_prize"): 20000, ("national", "second_prize"): 15000, ("national", "third_prize"): 10000,
        ("provincial", "grand_prize"): 10000, ("provincial", "first_prize"): 8000, ("provincial", "second_prize"): 6000, ("provincial", "third_prize"): 5000,
        ("municipal", "first_prize"): 5000, ("municipal", "second_prize"): 3000, ("municipal", "third_prize"): 2000,
    },
    "individual": {
        ("national", "grand_prize"): 20000, ("national", "first_prize"): 15000, ("national", "second_prize"): 12000, ("national", "third_prize"): 8000,
        ("provincial", "grand_prize"): 8000, ("provincial", "first_prize"): 6000, ("provincial", "second_prize"): 4000, ("provincial", "third_prize"): 3000,
        ("municipal", "first_prize"): 3000, ("municipal", "second_prize"): 2000, ("municipal", "third_prize"): 1000,
    },
}.items():
    for (level, rank), amount in amounts.items():
        DEFAULT_REWARD_RULES.append({
            "category": "teaching_competition",
            "subcategory": scope,
            "level": level,
            "rank": rank,
            "amount": amount,
            "annual_cap": 20000,
        })

DEFAULT_COMPETITIONS = [
    {"name": "全国高校教师教学创新大赛", "competition_type": "teacher", "max_level": "national", "organizer": "中国高等教育学会"},
    {"name": "全国高校青年教师教学竞赛", "competition_type": "teacher", "max_level": "national", "organizer": "中华全国总工会、教育部"},
    {"name": "全国高校思想政治理论课教学展示活动", "competition_type": "teacher", "max_level": "provincial", "organizer": "教育部办公厅"},
    {"name": "外研社教学之星大赛", "competition_type": "teacher", "max_level": "provincial", "organizer": "外语教学与研究出版社"},
    {"name": "全国高等院校英语教师教学基本功大赛", "competition_type": "teacher", "max_level": "provincial", "organizer": "全国高等师范院校外语教学与研究协作组"},
    {"name": "外教社杯全国高校外语教学大赛", "competition_type": "teacher", "max_level": "provincial", "organizer": "上海外语教育出版社、上海外国语大学"},
    {"name": "广西高校教育教学数字化大赛", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西壮族自治区教育厅"},
    {"name": "全区高校学习习近平新时代中国特色社会主义思想示范课堂", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西壮族自治区教育厅"},
    {"name": "广西高校思政课教师教学基本功暨精彩一课", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西壮族自治区教育工委、广西壮族自治区教育厅"},
    {"name": "广西高校思想政治工作优秀工作案例", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西壮族自治区教育厅办公室"},
    {"name": "广西高校壮美广西系列思政课示范课堂", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西壮族自治区教育厅"},
    {"name": "全区高校就业创业课程精彩一课教学大赛", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西壮族自治区教育厅"},
    {"name": "广西壮族自治区大中专院校体育教师教学技能大赛", "competition_type": "teacher", "max_level": "municipal", "organizer": "广西学校体育卫生艺术学会"},
]

_STUDENT_COMPETITION_NAMES = [
    ("中国国际大学生创新大赛", "national"), ("挑战杯全国大学生课外学术科技作品竞赛", "national"), ("挑战杯中国大学生创业计划大赛", "national"),
    ("中华职业教育创新创业大赛", "national"), ("ACM-ICPC国际大学生程序设计竞赛", "provincial"), ("全国大学生数学建模竞赛", "provincial"),
    ("全国大学生电子设计竞赛", "provincial"), ("全国大学生机械创新设计大赛", "provincial"), ("全国大学生智能汽车竞赛", "provincial"),
    ("全国大学生电子商务创新创意及创业挑战赛", "provincial"), ("中国大学生工程实践与创新能力大赛", "provincial"),
    ("外研社全国大学生英语系列赛", "provincial"), ("全国大学生创新创业训练计划年会展示", "provincial"), ("全国大学生机器人大赛RoboMaster/RoboCon", "provincial"),
    ("全国大学生市场调查与分析大赛", "provincial"), ("全国大学生先进成图技术与产品信息建模创新大赛", "provincial"), ("全国三维数字化创新设计大赛", "provincial"),
    ("西门子杯中国智能制造挑战赛", "provincial"), ("中国大学生服务外包创新创业大赛", "provincial"), ("中国大学生计算机设计大赛", "provincial"),
    ("中国高校计算机大赛", "provincial"), ("蓝桥杯全国软件和信息技术专业人才大赛", "provincial"), ("全国大学生光电设计竞赛", "provincial"),
    ("全国大学生集成电路创新创业大赛", "provincial"), ("全国大学生信息安全竞赛", "provincial"), ("中国大学生机械工程创新创意大赛", "provincial"),
    ("中国机器人大赛暨RoboCup机器人世界杯中国赛", "provincial"), ("中国软件杯大学生软件设计大赛", "provincial"), ("中美青年创客大赛", "provincial"),
    ("睿抗机器人开发者大赛", "provincial"), ("大唐杯全国大学生新一代信息通信技术大赛", "provincial"), ("华为ICT大赛", "provincial"),
    ("全国大学生嵌入式芯片与系统设计竞赛", "provincial"), ("全国高校商业精英挑战赛", "provincial"), ("学创杯全国大学生创业综合模拟大赛", "provincial"),
    ("中国高校智能机器人创意大赛", "provincial"), ("中国机器人及人工智能大赛", "provincial"), ("21世纪杯全国英语演讲比赛", "provincial"),
    ("iCAN大学生创新创业大赛", "provincial"), ("工行杯全国大学生金融科技创新大赛", "provincial"), ("中华经典诵写讲大赛", "provincial"),
    ("外教社杯全国高校学生跨文化能力大赛", "provincial"), ("百度之星程序设计大赛", "provincial"), ("全国大学生工业设计大赛", "provincial"),
    ("全国大学生计算机系统能力大赛", "provincial"), ("全国大学生物联网设计竞赛", "provincial"), ("全国大学生信息安全与对抗技术竞赛", "provincial"),
    ("全国大学生统计建模大赛", "provincial"), ("全国大学生数字媒体科技作品及创意竞赛", "provincial"), ("全国企业竞争模拟大赛", "provincial"),
    ("全国高等院校数智化企业经营沙盘大赛", "provincial"), ("全球校园人工智能算法精英大赛", "provincial"), ("科云杯全国大学生财会职业能力大赛", "provincial"),
    ("全国大学生机器人大赛RoboTac", "provincial"), ("世界技能大赛", "provincial"), ("世界技能大赛中国选拔赛", "provincial"),
    ("一带一路暨金砖国家技能发展与技术创新大赛", "provincial"), ("码蹄杯全国职业院校程序设计大赛", "provincial"), ("大学生讲思政课公开课展示活动", "provincial"),
    ("我心中的思政课全国高校大学生微电影展示活动", "provincial"), ("全国大学生职业规划大赛", "provincial"), ("全国大学生英语竞赛", "provincial"),
    ("全国大学生数学竞赛", "provincial"), ("世界职业院校技能大赛法律实务赛项", "provincial"), ("中华经典诵读系列比赛", "provincial"),
    ("华为鲲鹏昇腾系列竞赛", "provincial"), ("外教社词达人杯全国大学生英语词汇能力大赛", "provincial"), ("广西校园中华经典诵读比赛", "municipal"),
    ("全国公安院校智慧侦查技能大赛", "municipal"), ("黄河流域公安院校现场勘查比赛", "municipal"), ("警务英语大赛", "municipal"),
    ("大数据智能警务挑战赛", "municipal"), ("公安院校师生智慧交通警务教学技能创新大赛", "municipal"), ("广西八桂法声比赛", "municipal"),
    ("全区高校思想政治理论课研究性学习与实践性教学优秀成果评选活动", "municipal"), ("全国公安院校图像检验大赛", "municipal"),
    ("陆由杯广西高校大学生社会工作实务技能大赛", "municipal"), ("广西大学生应急救援技术大赛", "municipal"), ("南宁市创业大赛", "municipal"),
]

DEFAULT_COMPETITIONS.extend(
    {"name": name, "competition_type": "student", "max_level": level, "organizer": "按政策附件认定"}
    for name, level in _STUDENT_COMPETITION_NAMES
)
