/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminDashboard: typeof import('./src/components/admin/dashboard/AdminDashboard.vue')['default']
    AdminLogin: typeof import('./src/components/admin/login/AdminLogin.vue')['default']
    HrChangeRequests: typeof import('./src/components/admin/hr/HrChangeRequests.vue')['default']
    HrPerformance: typeof import('./src/components/admin/hr/HrPerformance.vue')['default']
    HrTeachers: typeof import('./src/components/admin/hr/HrTeachers.vue')['default']
    HrTitleRules: typeof import('./src/components/admin/hr/HrTitleRules.vue')['default']
    RewardBatches: typeof import('./src/components/admin/hr/RewardBatches.vue')['default']
    RewardRecognition: typeof import('./src/components/admin/hr/RewardRecognition.vue')['default']
    RewardRules: typeof import('./src/components/admin/hr/RewardRules.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
